"""Keep XTREMEX-IO-TABLE.html in step with sot/channels.csv.

    python docs/harness/sync_io_table.py           # rewrite the generated pin map
    python docs/harness/sync_io_table.py --check   # gate: exit 1 on any disagreement

sot/channels.csv is the single source of truth (Daniel, 2026-09-24). The IO table
is the visual face of it and must never disagree. Two things are checked:

  1. The generated "Pin map" block between the SOT:BEGIN / SOT:END markers is
     exactly what this script would write from the CSV today.
  2. Every hand-written row that names a channel and an ECU pin (td.chan +
     td.pin) agrees with the CSV: same pin, and "Available"/"spare" in the
     table only where the CSV says spare - and vice versa.

Fix a finding by editing the CSV first (if the CSV is wrong) and then the table.
"""
import csv, html, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
CSV = os.path.join(ROOT, "sot", "channels.csv")
HTML = os.path.join(ROOT, "XTREMEX-IO-TABLE.html")
BEGIN, END = "<!-- SOT:BEGIN", "<!-- SOT:END -->"

GROUP = [("Trigger", "trigger"), ("Temp", "temp"), ("An Volt", "volt"), ("Knock", "knock"),
         ("DI", "di"), ("Inj", "inj"), ("Ign", "ign"), ("Aux", "aux"), ("CAN", "can"),
         ("Comms", "can"), ("RS232", "can")]
CONN = [("ecu_a", "Connector A", "A"), ("ecu_b", "Connector B", "B"), ("ecu_com", "Comms port", "C")]


def rows():
    with open(CSV, newline="", encoding="utf-8") as f:
        return [r for r in csv.DictReader(f) if r["owner"] == "ECU"]


def colour(r):
    if r["class"] in ("spare", "nc"):
        return "tbd"
    if r["class"] in ("ground", "screen") or r["net"] == "GNDOUT":
        return "gnd"
    if r["class"] in ("power", "rail"):
        return "pwr"
    for pre, g in GROUP:
        if r["channel"].startswith(pre):
            return g
    return "pwr"


def pin_label(r, letter):
    n = re.sub(r"\D", "", r["pin"])
    return f"{letter}{n}"


def build_block(rs):
    out = [BEGIN + " generated by docs/harness/sync_io_table.py from sot/channels.csv - do not hand-edit -->",
           '<h2>Pin map — every ECU pin, straight from <code>sot/channels.csv</code></h2>',
           '<p class="note">Generated. Numeric order, not the physical connector face. '
           'Grey = spare or not connected. <code>shield</code> = which screen pin the drain lands on '
           '(A7 = SHIELD_A for loom A, B17 = SHIELD_B for loom B — never bridged).</p>']
    for conn, title, letter in CONN:
        rr = sorted([r for r in rs if r["conn"] == conn], key=lambda r: int(re.sub(r"\D", "", r["pin"]) or 0))
        out.append(f'<h3 class="pmh">{html.escape(title)} <span class="note">({len(rr)} pins)</span></h3>')
        out.append('<div class="pm">')
        for r in rr:
            p = pin_label(r, letter)
            net = r["net"] or "—"
            sh = f' · shield {r["shield"].upper()}' if r["shield"] else ""
            out.append(
                f'  <div class="pmc pm-{colour(r)}" title="{html.escape(r["label"])} · loom {html.escape(r["loom"])} · {html.escape(r["status"])}">'
                f'<b>{p}</b><span class="pmch">{html.escape(r["channel"])}</span>'
                f'<span class="pmnet">{html.escape(net)}</span>'
                f'<span class="pmlb">{html.escape(r["label"])}{html.escape(sh)}</span></div>')
        out.append("</div>")
    out.append(END)
    return "\n".join(out)


STYLE = """<style id="sot-pinmap">
  .pm{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:6px;margin:6px 0 14px}
  .pmc{background:#fff;border:1px solid #e2e8f0;border-left:6px solid #94a3b8;border-radius:6px;padding:5px 7px;font-size:11.5px;line-height:1.3}
  .pmc b{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px;margin-right:5px}
  .pmch{font-weight:600}.pmnet{display:block;font-family:ui-monospace,Menlo,Consolas,monospace;color:#334155}
  .pmlb{display:block;color:#64748b}.pmh{margin:10px 0 2px;font-size:14px}
  .pm-trigger{border-left-color:var(--trigger)}.pm-temp{border-left-color:var(--temp)}.pm-volt{border-left-color:var(--volt)}
  .pm-knock{border-left-color:var(--knock)}.pm-di{border-left-color:var(--di)}.pm-inj{border-left-color:var(--inj)}
  .pm-ign{border-left-color:var(--ign)}.pm-aux{border-left-color:var(--aux)}.pm-pwr{border-left-color:var(--pwr)}
  .pm-gnd{border-left-color:var(--gnd)}.pm-can{border-left-color:var(--can)}.pm-tbd{background:#f1f5f9;color:#94a3b8}
</style>"""


def strip_tags(s):
    return html.unescape(re.sub(r"<[^>]+>", "", s)).strip()


def expand_channels(chan):
    """'Inj 1–4' -> ['Inj 1'..'Inj 4'];  'Aux 9 / 10' -> ['Aux 9','Aux 10']."""
    chan = chan.replace("–", "-")
    m = re.fullmatch(r"([A-Za-z ]+?)\s*(\d+)\s*(?:-|/)\s*(\d+)", chan)
    if m:
        a, b = int(m.group(2)), int(m.group(3))
        step = 1 if b >= a else -1
        if "/" in chan:
            return [f"{m.group(1).strip()} {a}", f"{m.group(1).strip()} {b}"]
        return [f"{m.group(1).strip()} {i}" for i in range(a, b + step, step)]
    return [chan]


def expand_pins(pin):
    return re.findall(r"\b([AB]\d{1,2})\b", pin.replace("·", " "))


def hand_rows(doc):
    body = doc.split(BEGIN)[0] + (doc.split(END)[1] if END in doc else "")
    for tr in re.findall(r"<tr[^>]*>(.*?)</tr>", body, re.S):
        chan = re.search(r'<td class="chan">(.*?)</td>', tr, re.S)
        pin = re.search(r'<td class="pin">(.*?)</td>', tr, re.S)
        if not (chan and pin):
            continue
        cells = re.findall(r"<td[^>]*>(.*?)</td>", tr, re.S)
        func = strip_tags(cells[3]) if len(cells) > 3 else ""
        yield strip_tags(chan.group(1)), strip_tags(pin.group(1)), func


def check_hand(doc, rs):
    by_chan = {}
    for r in rs:
        if r["conn"] in ("ecu_a", "ecu_b"):
            by_chan.setdefault(r["channel"], []).append(r)
    errs = []
    for chan, pin, func in hand_rows(doc):
        chans, pins = expand_channels(chan), expand_pins(pin)
        if not pins or len(chans) != len(pins):
            continue  # shared rails (Gnd Out, Ground, Shield) are listed together; the pin map covers them
        for c, p in zip(chans, pins):
            srows = by_chan.get(c)
            if not srows:
                continue
            spins = {("A" if r["conn"] == "ecu_a" else "B") + re.sub(r"\D", "", r["pin"]) for r in srows}
            if p not in spins:
                errs.append(f"{c}: table says {p}, channels.csv says {'/'.join(sorted(spins))}")
                continue
            r = next(r for r in srows if ("A" if r["conn"] == "ecu_a" else "B") + re.sub(r"\D", "", r["pin"]) == p)
            says_free = bool(re.match(r"(available|spare)\b", func, re.I))
            is_free = r["class"] in ("spare", "nc")
            if says_free and not is_free:
                errs.append(f"{c} {p}: table says '{func}', channels.csv says {r['label']} ({r['status']})")
            if is_free and not says_free:
                errs.append(f"{c} {p}: channels.csv says spare, table says '{func}'")
    return errs


def main():
    check = "--check" in sys.argv
    rs = rows()
    with open(HTML, encoding="utf-8", newline="") as f:
        doc = f.read()
    block = build_block(rs)
    errs = []
    if BEGIN in doc and END in doc:
        cur = doc[doc.index(BEGIN):doc.index(END) + len(END)]
        new = doc.replace(cur, block)
    else:
        errs.append("generated pin-map block missing")
        anchor = "<h2>Inputs — Analog</h2>"
        new = doc.replace(anchor, block + "\n\n" + anchor, 1)
    if 'id="sot-pinmap"' not in new:
        new = new.replace("</head>", STYLE + "\n</head>", 1)
    if new != doc:
        errs.append("pin-map block is stale against sot/channels.csv")
    errs += check_hand(new, rs)
    if check:
        for e in errs:
            print("  MISMATCH", e)
        print(f"IO table vs channels.csv: {len(errs)} mismatch(es)")
        sys.exit(1 if errs else 0)
    if new != doc:
        with open(HTML, "w", encoding="utf-8", newline="") as f:
            f.write(new)
        print("rewrote pin map in XTREMEX-IO-TABLE.html")
    hand = check_hand(new, rs)
    for e in hand:
        print("  MISMATCH", e)
    print(f"hand-written rows: {len(hand)} mismatch(es) - fix these by hand")


if __name__ == "__main__":
    main()
