#!/usr/bin/env python3
"""Embed the four ST185 harness JSONs into apps/harness-overlay/data.js."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HARNESS_DIR = ROOT / "docs" / "harness"
OUT = Path(__file__).resolve().parent / "data.js"

FILES = [
    ("Signal", "ST185-Signal.harness", "#5b8def"),
    ("Power", "ST185-Power.harness", "#e8b849"),
    ("CAN", "ST185-CAN.harness", "#3dd68c"),
    ("EngineRoom-C", "ST185-EngineRoom-C.harness", "#c084fc"),
]


def slim_device(obj: dict, kind: str) -> dict:
    sp = obj.get("schematicPosition") or {}
    return {
        "id": obj["id"],
        "label": obj.get("label") or obj.get("signal") or obj["id"],
        "kind": kind,
        "x": sp.get("x"),
        "y": sp.get("y"),
    }


def slim_wire(w: dict) -> dict:
    pts = []
    for lp in w.get("layoutPoints") or []:
        sp = lp.get("schematicPosition") or {}
        if "x" in sp and "y" in sp:
            pts.append({"x": sp["x"], "y": sp["y"]})
    return {
        "id": w["id"],
        "color": w.get("color"),
        "source": w.get("source") or {},
        "target": w.get("target") or {},
        "layoutPoints": pts,
    }


def load_harness(path: Path) -> dict:
    raw = json.loads(path.read_text(encoding="utf-8"))
    devices = []
    missing = []
    for kind, key in (
        ("connector", "connectors"),
        ("splice", "splices"),
        ("terminal", "terminals"),
        ("resistor", "resistors"),
    ):
        for obj in raw.get(key) or []:
            d = slim_device(obj, kind)
            if d["x"] is None or d["y"] is None:
                missing.append({"id": d["id"], "kind": kind, "label": d["label"]})
            else:
                devices.append(d)
    wires = [slim_wire(w) for w in raw.get("wires") or []]
    return {
        "devices": devices,
        "wires": wires,
        "missingSchematicPosition": missing,
        "counts": {
            "devices": len(devices),
            "wires": len(wires),
            "missingSchematicPosition": len(missing),
        },
    }


def main() -> None:
    payload = {"harnesses": []}
    for key, filename, color in FILES:
        path = HARNESS_DIR / filename
        data = load_harness(path)
        payload["harnesses"].append(
            {
                "key": key,
                "file": filename,
                "color": color,
                **data,
            }
        )
    text = (
        "/* Auto-generated by build_data.py — do not edit by hand. */\n"
        "window.HARNESS_DATA = "
        + json.dumps(payload, indent=2, ensure_ascii=False)
        + ";\n"
    )
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    for h in payload["harnesses"]:
        c = h["counts"]
        print(
            f"  {h['key']:14} devices={c['devices']:3} wires={c['wires']:3} "
            f"missingPos={c['missingSchematicPosition']}"
        )


if __name__ == "__main__":
    main()
